### ISSUE TITLE
Pass environment variables to plugin during version build/installation

### ISSUE THREAD

**Issue by ricardoseriani** [jdx/rtx#1012] opened 2023-11-22 18:30 UTC
Hi
How are you?

Before anything, thanks for this amazing software.
I'm using an asdf plugin (https://github.com/tsuyoshicho/asdf-vim) to manage vim versions. 
That plugin allows passing some variables to be used during vim build, such as ASDF_VIM_TYPE and ASDF_VIM_CONFIG, as you can see in the section Installation Variable in README.md.
There is any way that I can set this in .rtx.toml, so when I backup this file and restore in another PC it's install the same way ?

Thanks in advance.

Best regards.
Ricardo Seriani

**Comment by jdx** [comment] 2023-11-22 18:54
duplicate of https://github.com/jdx/rtx/issues/702

**Closed by jdx** 2023-11-22 18:54 UTC
Labels: enhancement
