### ISSUE TITLE
Support installation with cargo binstall

### ISSUE THREAD

**Issue by yodatak** [jdx/rtx#884] opened 2023-09-07 21:13 UTC
Many rust tool are downloadable with cargo bininstall i can be interesting to support the installation of program with cargo binstall

https://github.com/cargo-bins/cargo-binstall
what do you think ?

**Comment by yodatak** [comment] 2023-10-23 14:31
It not realy what i need like i want to have a list like i want like 
the latest ripgrep
the latest jetp
and to install them from cargo binstall not sure if explain well ^

**Comment by jdx** [comment] 2023-12-02 07:58
it sounds like you just want to use rtx as a generic `cargo binstall` utility?

**Comment by yodatak** [comment] 2023-12-07 08:16
Yes exactly to permit some cool program to be installed like rt does

**Comment by jdx** [comment] 2023-12-12 01:13
I'm going to close as a duplicate of #580

**Closed by jdx** 2023-12-12 01:13 UTC
Labels: enhancement
